### ISSUE TITLE
Support request: would you help me install git-ssb?

### ISSUE THREAD

**Issue by rdbartlett** [noffle/git-ssb-intro#2]
hello! I am a patchwork user and a github user. so I want to be a git-ssb user.

I ran `npm install -g git-ssb`

and got this response:

```
/Users/rich/.nvm/versions/node/v4.4.7/bin/git-ssb -> /Users/rich/.nvm/versions/node/v4.4.7/lib/node_modules/git-ssb/bin/git-ssb
/Users/rich/.nvm/versions/node/v4.4.7/bin/git-remote-ssb -> /Users/rich/.nvm/versions/node/v4.4.7/lib/node_modules/git-ssb/bin/git-remote-ssb

> sodium-native@2.1.3 install /Users/rich/.nvm/versions/node/v4.4.7/lib/node_modules/git-ssb/node_modules/sodium-native
> node-gyp-build "node preinstall.js" "node postinstall.js"

/Users/rich/.nvm/versions/node/v4.4.7/lib
└─┬ git-ssb@2.3.6 
  ├─┬ git-remote-ssb@2.0.4 
  │ └─┬ pull-git-remote-helper@2.0.0 
  │   └── progress@1.1.8 
  ├─┬ git-ssb-web@2.8.0 
  │ ├── asyncmemo@1.0.0 
   [etc...]
```

Then I restarted Patchwork. Now when I visit `http://localhost:7718/` I get an error "This site can’t be reached. localhost refused to connect." And when I run `git-ssb web` I get this error:

```
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/rich/.nvm/versions/node/v4.4.7/lib/node_modules/git-ssb/node_modules/git-ssb-web/index.js:18:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

**Comment by rdbartlett** [comment]
Fixed! it needed a more recent version of node. I switched to the latest version I have (` nvm use v6.3.1`) and it works now :)

**Comment by hackergrrl** [comment]
That's awesome! Thank you for documenting the problem and the fix. :heart:  See you on git-ssb!

**Comment by rdbartlett** [comment]
And thank you for the warm greeting!
