### ISSUE TITLE
TypeError: Cannot read property 'unbox' of undefined

### ISSUE THREAD

**Issue by MrChico** [noffle/git-ssb-intro#6]
I would post this at https://git.scuttlebot.io/%25n92DiQh7ietE%2BR%2BX%2FI403LQoyf2DtR3WQfCkDKlheQU%3D.sha256 but I can't for reasons that will become clear.

When trying to access the web interface to git-ssb at localhost:7718, the `git-ssb web` process crashes with the following error message:
```
Listening on http://localhost:7718/
~/.npm-global/lib/node_modules/git-ssb/node_modules/git-ssb-web/lib/util.js:201
    sbot.private.unbox(msg.value.content, function (err, content) {
                 ^

TypeError: Cannot read property 'unbox' of undefined
    at Object.u.decryptMessage (~/.npm-global/lib/node_modules/git-ssb/node_modules/git-ssb-web/lib/util.js:201:18)
    at ~/.npm-global/lib/node_modules/git-ssb/node_modules/git-ssb-web/lib/util.js:232:7
    at ~/.npm-global/lib/node_modules/git-ssb/node_modules/pull-paramap/index.js:41:11
    at PacketStreamSubstream.weird.read (~/.npm-global/lib/node_modules/git-ssb/node_modules/muxrpc/pull-weird.js:33:7)
    at PacketStream._onstream (~/.npm-global/lib/node_modules/git-ssb/node_modules/packet-stream/index.js:204:12)
    at PacketStream.write (~/.npm-global/lib/node_modules/git-ssb/node_modules/packet-stream/index.js:135:41)
    at ~/.npm-global/lib/node_modules/git-ssb/node_modules/muxrpc/pull-weird.js:56:15
    at ~/.npm-global/lib/node_modules/git-ssb/node_modules/pull-stream/sinks/drain.js:24:37
    at ~/.npm-global/lib/node_modules/git-ssb/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:17:11
    at Object.cb (~/.npm-global/lib/node_modules/git-ssb/node_modules/packet-stream-codec/index.js:111:11)
```
which makes further interaction with the web interface impossible

**Comment by hackergrrl** [comment]
Try installing the ssb-private plugin:

sbot plugins.install ssb-private

and restart 'sbot server'.
